
ALTER TABLE public.deals
  ADD COLUMN IF NOT EXISTS photos text[],
  ADD COLUMN IF NOT EXISTS pipeline_stage text,
  ADD COLUMN IF NOT EXISTS total_sqft numeric,
  ADD COLUMN IF NOT EXISTS price_per_sqft numeric,
  ADD COLUMN IF NOT EXISTS gross_scheduled_rent numeric,
  ADD COLUMN IF NOT EXISTS occupancy_pct numeric,
  ADD COLUMN IF NOT EXISTS in_place_cap_rate numeric,
  ADD COLUMN IF NOT EXISTS expense_ratio numeric,
  ADD COLUMN IF NOT EXISTS grm numeric,
  ADD COLUMN IF NOT EXISTS stabilized_rent numeric,
  ADD COLUMN IF NOT EXISTS renovation_budget_per_unit numeric,
  ADD COLUMN IF NOT EXISTS total_capex numeric,
  ADD COLUMN IF NOT EXISTS stabilized_noi numeric,
  ADD COLUMN IF NOT EXISTS stabilized_cap_rate numeric,
  ADD COLUMN IF NOT EXISTS projected_irr numeric,
  ADD COLUMN IF NOT EXISTS equity_multiple numeric,
  ADD COLUMN IF NOT EXISTS year1_coc numeric,
  ADD COLUMN IF NOT EXISTS dscr numeric,
  ADD COLUMN IF NOT EXISTS ltv numeric,
  ADD COLUMN IF NOT EXISTS interest_rate numeric,
  ADD COLUMN IF NOT EXISTS loan_term_years numeric,
  ADD COLUMN IF NOT EXISTS hold_period_years numeric,
  ADD COLUMN IF NOT EXISTS exit_cap numeric,
  ADD COLUMN IF NOT EXISTS rent_comps jsonb,
  ADD COLUMN IF NOT EXISTS sales_comps jsonb,
  ADD COLUMN IF NOT EXISTS documents jsonb;
